# Generated by Django 5.2 on 2025-04-08 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Financas', '0002_remove_nota_fiscal_fornecedor_fluxo_caixa_produto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fluxo_caixa',
            name='produto',
        ),
        migrations.AddField(
            model_name='fluxo_caixa',
            name='total_despesas',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fluxo_caixa',
            name='total_vendas',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
