# Generated by Django 5.2 on 2025-04-09 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Financas', '0003_remove_fluxo_caixa_produto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricasFinanceiras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo_caixa', models.DecimalField(decimal_places=2, max_digits=12)),
                ('saldo_caixa_variacao', models.DecimalField(decimal_places=2, max_digits=5)),
                ('valor_a_receber', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valor_a_receber_variacao', models.DecimalField(decimal_places=2, max_digits=5)),
                ('valor_a_pagar', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valor_a_pagar_variacao', models.DecimalField(decimal_places=2, max_digits=5)),
                ('lucro_mensal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('lucro_mensal_variacao', models.DecimalField(decimal_places=2, max_digits=5)),
                ('valor_em_estoque', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valor_total_vendas', models.DecimalField(decimal_places=2, max_digits=12)),
                ('qtd_fornecedores', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Métricas Financeiras',
            },
        ),
    ]
