# Generated by Django 5.2 on 2025-04-09 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Financas', '0004_metricasfinanceiras'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('descricao', models.CharField(max_length=100)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída')], max_length=10)),
                ('categoria', models.CharField(max_length=50)),
                ('forma_pagamento', models.CharField(max_length=50)),
            ],
        ),
    ]
