# Generated by Django 5.2 on 2025-04-09 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Financas', '0005_transacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metricasfinanceiras',
            name='saldo_caixa',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
