# Generated by Django 5.2 on 2025-04-09 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Financas', '0006_alter_metricasfinanceiras_saldo_caixa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fluxo_caixa',
            options={'ordering': ['ordem']},
        ),
        migrations.AlterModelOptions(
            name='transacao',
            options={'ordering': ['-data'], 'verbose_name_plural': 'Transações'},
        ),
        migrations.RemoveField(
            model_name='transacao',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='transacao',
            name='forma_pagamento',
        ),
        migrations.AddField(
            model_name='fluxo_caixa',
            name='mes',
            field=models.CharField(default=0, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fluxo_caixa',
            name='ordem',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transacao',
            name='contraparte',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transacao',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('recebido', 'Recebido'), ('atrasado', 'Atrasado')], default='pendente', max_length=8),
        ),
        migrations.AddField(
            model_name='transacao',
            name='vencimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fluxo_caixa',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='descricao',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='tipo',
            field=models.CharField(choices=[('receita', 'Receita'), ('despesa', 'Despesa')], max_length=7),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
